---
title: "Ecología de poblaciones"
description: "Licenciatura en Ecología"
author: "Gerardo Martín"
output:
   prettydoc::html_pretty:
      theme: cayman
      highlight: github
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Ver [Encuadre](Encuadre.pdf) y [Programa del curso](Programa.pdf)
    
1. Introducción a la ecología de poblaciones

    - [Preguntas centrales de la ecología de poblaciones](Unidad-1/Preguntas-centrales.pdf)
    
    - [Definición de individuo](Unidad-1/Individuos.pdf)
          
    - [Definición de población](Unidad-1/Poblacion.pdf)
    
    - [Ciclos de vida de los organismos](Unidad-1/Ciclos-vida.pdf)
    
2. La demografía

    - [Métodos para determinar el tamaño poblacional](Unidad-2/Estimacion-tamano.pdf)
    
    - [Práctica de estimación de tamaño poblacional](Unidad-2/Practica-estimacion.html)
    
    - [Tablas de vida](Unidad-2/Tablas-vida.pdf)

    - [Curvas de supervivencia](Unidad-2/Curvas-sup.pdf)
    
    - [Matrices de proyección poblacional](Unidad-2/Matrices-proyeccion.pdf)

    - [Modelos de crecimiento poblacional: competencia intraespecífica](Unidad-2/Modelos-crecimiento.pdf)
    
    - [Práctica de competencia intraespecífica](Unidad-2/Practica-intra.html)
    
    - [Regulación de las poblaciones](Unidad-2/Regulacion-poblaciones.pdf)
    
3. Evolución de historias de vida

    - [Componentes de la historia de vida](Unidad-3/Componentes-historia.pdf)
    
    - [Teoría de la selección *r* y *K*](Unidad-3/Seleccion-r-K.pdf)
    
    - [Compromisos](Unidad-3/Compromisos.pdf)
    
4. Metapoblaciones y Ecología Espacial

    - [Formas de dispersión](Unidad-4/Formas-dispersion.pdf)
    
    - [Patrones de distribución y migración](Unidad-4/Patrones-distr-migr.pdf)
    
    - [Dispersión y demografía de metapoblaciones](Unidad-4/Dispersion-demografia.pdf)
    
5. Conservación y manejo de poblaciones
  
    - [Análisis de viabilidad de poblaciones](Analisis-viabilidad.pdf)