---
title: "Práctica de estimación de tamaño poblacional"
author: "Gerardo"
date: "2023-03-21"
output:
        bookdown::html_document2:
            toc: true 
            number_sections: true
            toc_float: true
            theme: flatly
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Materiales de la práctica

1. Dos puños de frijoles blancos y dos puños de frijoles más oscuros (bayos de preferencia)

2. Un calcetín

3. Una cuchara sopera y una cucharita

4. Plumones marcadores permanentes de tres colores diferentes

# Intrucciones

## Experimento 1 

1. Introduce uno de los puños de frijoles blancos en el calcetín.

2. Utilizando primero la cucharita, saca una muestra de frijoles del calcetín.

3. Cuenta los frijoles que obtuviste y márcalos con alguno de los plumones. Registra el número de frijoles obtenido y devuélvelos ya marcados al calcetín.

4. Vuelve a tomar una muestra con la misma cuchara y cuéntalos. Registra el número total de frijoles y el número de frijoles con marcas que obtuviste en esta segunda muestra.

5. Repite el proceso otras dos veces, pero utilizando los plumones de diferente color para identificar si se trata de la segunda ó tercera vez.

6. Al finalizar el proceso la tercera vez, cuenta todos los frijoles que hay en el calcetín, y cuenta también los frijoles que no tienen ninguna marca.

7. Utilizando el segundo puño de frijoles repite el proceso de los puntos 1-6 utilizando la cuchara sopera.

## Experimento 2

1. Cuenta 120 frijoles, 40 blancos y 80 oscuros sin marcar e introdúcelos en el calcetín

2. Utilizando la cuchara grande toma una muestra, márcalos todos y regresalos al calcetín

3. Ejecuta dos veces el programa [`simulacion.R`](simulacion.R) y extrae o introduce el número de frijoles blancos (juveniles) y negros (adultos) que el programa te indica

    - Para ejecutar este programa se necesitan varios argumentos, por defecto ya todos estos argumentos tienen vaores, así que la primera vez que se ejecuta, sólo es necesario llamarlo. No obstante, para las veces subsecuentes es necesario sustituir los argumentos `n.juv` y `n.ad` por los resultados de la ejecución de la primera vez `total.juv` y `total.ad`. Los resultados de la ejecución que te indican cuántos hay que meter o sacar de cada tipo son `d.juv` y `d.ad`.

4. Utilizando la cuchara grande toma una muestra y cuenta el número de frijoles no marcados y de frijoles marcados en el paso anterior

5. Repite el paso **3** dos veces

6. Repite los pasos **2-4** utilizando marcador dediferente color para distinguir estas marcas nuevas de las utilizadas anteriormente (igual que en el experimento 1).  

# Análisis

Utilizando los datos colectados cada vez que realizaste la *captura*, *marca* y *recaptura*, realiza el siguientes cálculos:

$$ N = \frac{nK}{k} $$

donde:

- $N$ es el número total de animales en la población
- $n$ es el número de animales capturados en la primera visita
- $K$ es el número de animales capturados en la segunda visita
- $k$ es el número de recapturados (que fueron marcados en la primera visita)

# Redacción de reporte

Para entregar esta tarea deberás de redactar un reporte, describiendo los métodos, resultados, discusión, conclusiones y bibliografía. En la discusión y conclusiones deberás responder [las preguntas](Preguntas-estimacion.html).

*Es obligatorio incluir una sección de bibliografía, y no se aceptarán trabajos que hagan copia y pega de trabajos escritos por alguien más ó por la IA. Incluye además las citas dentro del texto, de modo que toda la bibliografía citada aparezca en la sección de referencias.*
